apiVersion: batch/v1
kind: Job
metadata:
  name: recurring-task-job
spec:
  template:
    spec:
      containers:
      - name: create-task
        image: yrs9480/testapp:latest
        command: ["python", "./main.py", "create", 
                   "--id={{ .Values.createTaskJob.id }}", 
                   "--name={{ .Values.createTaskJob.name }}", 
                   "--cron_schedule={{ .Values.createTaskJob.cronSchedule }}"]
      restartPolicy: Never
  backoffLimit: 4
