apiVersion: batch/v1
kind: Job
metadata:
  name: non-recurring-task-job
spec:
  template:
    spec:
      containers:
      - name: non-recurring-task
        image: yrs9480/testapp:latest
        command: ["python", "./main.py", "create", 
                   "--id={{ .Values.nonRecurringTaskJob.id }}", 
                   "--name={{ .Values.nonRecurringTaskJob.name }}", 
                   "--execution_time={{ .Values.nonRecurringTaskJob.executionTime }}"]
      restartPolicy: Never
  backoffLimit: 4
