apiVersion: batch/v1
kind: Job
metadata:
  name: create-task-job
spec:
  template:
    spec:
      containers:
      - name: create-task
        image: yrs9480/testapp:latest
        command: ["python", "./main.py", "create", "--id=99", "--name=NewTask", "--cron_schedule=*/2 * * * *"]
      restartPolicy: Never
  backoffLimit: 4

