apiVersion: batch/v1
kind: Job
metadata:
  name: create-task-job
spec:
  template:
    spec:
      containers:
      - name: create-task
        image: yrs9480/taskapp:latest
        command: ["python", "./main.py", "create", "--name=NewTask", "--execution_time=2024-03-14 18:55:30"]
      restartPolicy: Never
  backoffLimit: 4
