apiVersion: batch/v1
kind: Job
metadata:
  name: read-task-job
spec:
  template:
    spec:
      containers:
      - name: read-task
        image: yrs9480/testapp:latest
        command: ["python", "./main.py", "view"]
      restartPolicy: Never
  backoffLimit: 4
