apiVersion: v1
kind: Pod
metadata:
  name: {{ include "taskchart.fullname" . }}-mysql-pod
  labels:
    app: mysql
  {{- include "taskchart.labels" . | nindent 4 }}
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: test
    - name: MYSQL_DATABASE
      value: mydb
    image: mysql:latest
    name: mysql
    ports:
    - containerPort: 3306