apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
  {{- include "taskchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysqlService.type }}
  selector:
    app: mysql
  {{- include "taskchart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mysqlService.ports | toYaml | nindent 2 }}